### ISSUE TITLE
error cms

### ISSUE THREAD

**Issue by matiaspicca** [ovflowd/chocolatey#364]
Pongo la cms

![image](https://user-images.githubusercontent.com/15640713/33092054-bcaba9b8-ced7-11e7-8040-947063db9409.png)
 configuro documentroot puse db arcturus y php artisan migrate y me sale esto !! 

![image](https://user-images.githubusercontent.com/15640713/33092048-b23d9482-ced7-11e7-924d-8eb56e447b1c.png)

**Comment by matiaspicca** [comment]
usoo iis php 7.1

**Comment by matiaspicca** [comment]
![image](https://user-images.githubusercontent.com/15640713/33092145-0b7dc062-ced8-11e7-9ee5-1af7ed0df8d0.png)

**Comment by TheOmanNorge** [comment]
![iis](https://user-images.githubusercontent.com/15328445/33134839-0e275c82-cfa1-11e7-984f-d7e22b4ee31e.png)

What happens if you change physical path to; %SystemDrive%\inetpub\wwwroot\public ?
Ive never installed Chocolatey on IIS so don't know. 

About the 500 error, possible you can find out what is causing it?
Is there some kind of error logs? If so try to find it.

**Comment by matiaspicca** [comment]
si eso lo hize pero lo mismo aparece

**Comment by ovflowd** [comment]
Can you give us the IIS Logs?

**Comment by ovflowd** [comment]
Hey @matiaspicca check this tutorial: https://github.com/sant0ro/chocolatey/wiki/New-Tutorial
