### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by talhayetkin** [ovflowd/chocolatey#368]
Can anyone help me with this problem? [http://prntscr.com/hl1eat](url) ?

**Comment by TheOmanNorge** [comment]
What webserver are you using? Xampp, IIS, ?  😀 

I know how do to it on IIS and cPanel. Might be able to help you.
Please tell me. 👍

**Comment by TheOmanNorge** [comment]
Example for changing documentroot on IIS. 
If you have something else please say so.

Have all the requirements in order to run Chocolatey CMS. (PHP 7.1, mysql and so on) 
Make sure you have uploaded the content of Chocolatey CMS into your root folder, as in this case is wwwroot

For this tutorial I'm running PHP v7.1.7

Example:
![wwwroot](https://user-images.githubusercontent.com/15328445/33801374-13e42d8c-dd5a-11e7-9a1c-5ad651c1586f.png)

As you see in the image there is a folder called `public` fantastic!

Open up IIS Manager and go to this location: 
`Internet Imformation Services -> Sites -> Default Web Site -> Basic settings. `

You want to change the Physical Path: 

Before and After example images.

> Before

![before](https://user-images.githubusercontent.com/15328445/33801378-37182376-dd5a-11e7-860e-4136d544d553.png)

> After [Needs to be changed to this]

![after](https://user-images.githubusercontent.com/15328445/33801379-3b47c000-dd5a-11e7-8a6e-5522ccd50675.png)


Go to your php.ini and find this:
` allow_url_fopen & allow_url_include  ` and set those values to On

You get error messages that is saying 500 error.
Go to your php.ini file and locate: 
`display_errors` set value to On

Alright, I've got the error messages on my screen saying something about permissions
Example: 

![permission_failed](https://user-images.githubusercontent.com/15328445/33801382-579442c4-dd5a-11e7-8003-d04a68c368df.png)

Right click on wwwroot or at your selected rootfolder. 
Click `Properties` & then Security

Select `Users` and give him full permissions.
Example:

![users](https://user-images.githubusercontent.com/15328445/33801398-9dcca588-dd5a-11e7-9e02-e4fbd045e0c0.png)



> Oy! I've now got this error!!! plz help.. 

![whops](https://user-images.githubusercontent.com/15328445/33801567-7d141092-dd5f-11e7-8b37-daf6c1cb1d47.png)

Check your chocolatey.php file inside the Config folder.

Check and see that your site url is alright.
Didnt help? 

Make sure your .env details is correct.
Upload .sql database file `arcturus-1.11.0.sql` to your db. 

Install Composer
https://getcomposer.org/

Open up CMD
Remember to change location on cmd. 
` Example: cd c:\inetpub\wwwroot` 
Execute: php artisan migrate

I know I also went out of subject right here now, and didnt stay completely on the topic of documentroot.
Just wanted to give you these tips, in case you come across the same problems as me. 

Enjoy

![enjoy](https://user-images.githubusercontent.com/15328445/33801401-a2c28cba-dd5a-11e7-8031-32185a14c503.png)

**Comment by talhayetkin** [comment]
Can you make a tutorial how to run php artisan migrate ?

**Comment by TheOmanNorge** [comment]
How to install Composer and Migrating. 
Sorry if this tutorial is not good. Did this in a hurry! 

> Go to https://getcomposer.org/download/
> Install Composer_Setup.exe

`Be sure that you select the right PHP version! Very important!`
`This is for me, might be different from yours!`

![composer_install1](https://user-images.githubusercontent.com/15328445/33804144-f5e2768c-dd9e-11e7-8e91-1378832da3c6.png)


Restart your PC after installation.

Now go and open console. CMD.
Go and select the path. Run `cd pathtoyour-rootfolder`
Example for my system: `cd C:\inetpub\wwwroot`

When your there. 
Run `composer install` and after that run `php artisan migrate`


> Hi! But I now got this error [Fileinfo does not exist.]
Go to php.ini and all the way down to extentions. 
Enable `extension=php_fileinfo.dll`

Error: 
![cmd_error](https://user-images.githubusercontent.com/15328445/33804053-5a5be942-dd9d-11e7-9612-3e63e0e4f13f.png)

How to fix: 
![fileinfo_fix](https://user-images.githubusercontent.com/15328445/33804054-603bf28a-dd9d-11e7-92b6-d994a701f462.png)


Take a look at my images down here. It might be to help if you don't understand. 👍 

`You can open up CMD and jump right into your location by doing this: `
![openupcmd](https://user-images.githubusercontent.com/15328445/33804070-990c7f3a-dd9d-11e7-8aaf-db2767cd3915.png)

`This is also a way to change path:`
![cmd2](https://user-images.githubusercontent.com/15328445/33804073-9ff67ec2-dd9d-11e7-8484-f3863f524fed.png)

By typing in `dir` it then shows whats inside the location your at:
![directory_wwwroot](https://user-images.githubusercontent.com/15328445/33804063-8bd314fa-dd9d-11e7-9bae-4cbec44d5843.png)

`Running composer install`
![composer_install2](https://user-images.githubusercontent.com/15328445/33804074-a55b638c-dd9d-11e7-9b1a-7f747cde0e4c.png)

`Downloading files [composer install]`
![composer_install3](https://user-images.githubusercontent.com/15328445/33804075-ae98f888-dd9d-11e7-9e78-9350fbd3326d.png)

`Running php artisan migrate`
![php_artisan_migrate2](https://user-images.githubusercontent.com/15328445/33804079-c24f94b8-dd9d-11e7-96e9-97f523855e69.png)

**Comment by ovflowd** [comment]
Amazing setup! @TheOmanNorge adding it on the Chocolatey Wiki!

**Comment by TheOmanNorge** [comment]
@sant0ro 
Thank you. 😅 

It's not the greatest tutorial, since i feel that with all the images it's kinda messy. 
And I would have tried to have done a much better job with the tutorial if I did know before hand that It would be going into the tutorial section one day.

Just saying in case people one day is complaining about it.
Anyway if that is the case one day, I'll be here superfast and helping out if someone didnt understand it. 

But I appreciate that you added it, and again thank you! 👍

**Comment by ovflowd** [comment]
@TheOmanNorge if you want to edit. I sent to you an invite to be collaborator of the project. Just accept it and you can by yourself edit it :)

https://github.com/sant0ro/chocolatey/invitations

**Comment by TheOmanNorge** [comment]
Done. 
Thanks, I'll find time some day and do it. 👍
