### ISSUE TITLE
Client flash player blocked [FIXED] -- 76% Client disconnect

### ISSUE THREAD

**Issue by Dazkor** [ovflowd/chocolatey#376]
Here: https://imgur.com/a/79Vzk

When I enter the client with the correct configuration the flash player locks the page and is in the configuration of the exceptions in chrome and remains blank

**Comment by TheOmanNorge** [comment]
What is your swf settings? 
Go to your chocolatey.php and find them.

Paste them here. 
Are you using the latest version of Chocolatey or a older version?

**Comment by Dazkor** [comment]
Settings: https://pastebin.com/MSHkbAA3

**Comment by TheOmanNorge** [comment]
I can tell you right now... 
Remove the / in the end of the furnidata.xml line. 

![slash](https://user-images.githubusercontent.com/15328445/34501024-659b1fee-f00d-11e7-92d1-313a1dc9c708.png)
Or else you will get a disconnection problem later on when you have fixed your current problem.

Also make sure your PRODUCTION-### is correct and Habbo.swf file.

Since it's not public, and I can't check. Can you post and image on what you have inside your Gordon folder? Are you 100% sure everything is correct? 

Where is your swf folder located, outside the folder /public or inside? 

Did you just copy the line from up there or are you 100% that is correct?
Image: 

![copy-](https://user-images.githubusercontent.com/15328445/34500840-b0e2f72a-f00c-11e7-8211-6ddf2bc1b3ac.png)

**Comment by Dazkor** [comment]
I put my swf folder in the public folder and it fixed itself, but I have a problem that reaches 76% the client and it disconnects

**Comment by TheOmanNorge** [comment]
Did you remove the / of the furnidata.xml file as I told you?

Check developertools and see if that can give you any clues to what is causing it. 
Btw are you using the latest version of Arcturus and have you downloaded the right Habbo.swf file?

Also if you are using the latest version of Chocolatey then that might be the reason why it happens.
The issue on the latest release has not been fixed but try using this version instead if you're using the latest version.

https://github.com/sant0ro/chocolatey/releases/tag/3.000N

This might be one of the reasons because of the disconnect.

**Comment by Dazkor** [comment]
https://imgur.com/a/Q8gFy

Now this happens when installing the version of the cms that you gave me [fixed]

----------------
https://imgur.com/a/d0dXa

Now it does not load anything in the client [FIXED]

------------------

Everything is fixed, thanks for your help I thank you

**Comment by TheOmanNorge** [comment]
No problem, I'm happy that your issue is fixed. 👍
If you have any more issues related to Chocolatey, don't hesitate to open a new ticket.

Closing ticket, since it's resolved. 😄
