### ISSUE TITLE
SWF Furni 404 error.

### ISSUE THREAD

**Issue by berkibap** [ovflowd/chocolatey#393]
Hey guys, 

So I have ran to this issue today.Fresh installed everything, but when ı click to catalog items I get 404 errors on console. It does some id like /44180/ and they don't exist.

Could you help? Thanks.

**Comment by ovflowd** [comment]
Probably you're using a wrong external_variables for your SWF. Try using another pack. That happens because the DCR download pattern on your external_variables doesn't matches the structure of your hof_furni folder.

**Comment by berkibap** [comment]
downloaded plus' swf files, now on console it says Analyzing library "hh_human_item", content is not a MovieClip and Analyzing library "hh_human_body", content is not a MovieClip]. I tried multiple ones but stuck on 76 now.

**Comment by ovflowd** [comment]
This thing of movie clip it's not a problem. It's normal, because generally SWF's were intended to be a kind of streaming content. But in fact they became popular for development of games, in the past Sockwave was used for that, after Shockwave, Flash became famous for web gaming, and now, we have canvas.

Habbo still uses Flash (SWF).

Your 76% problem can in fact be many things. I would recommend you to follow this guide: https://github.com/ovflowd/chocolatey/blob/master/SUPPORT.md

Basically I need you to attach a HAR file. That would me allow to se full network logs of your Client.

Things that your 76% could be:

1. Wrong Habbo.swf version
2. Habbo.swf isn't RC4 patched
3. Wrong crossdmain.xml entries
4. Your external_variables points to non existent files
5. The SWF cannot find the furnidata.xml or productdata.xml
6. The Emulator isn't listening to the world, if you're using Arcturus, make sure that the bind address is 0.0.0.0
7. You configured a wrong port on the client, or the port in the emulator isn't the same as in the client
8. Your firewall or ISP is blocking.

Give a check on these things, also on the chocolatey.ph (configuration file) if everything is right.

Big hugs :)

**Comment by berkibap** [comment]
Amazingly, everything worked after I've reinstalled chocolatey. Thanks for helps, @ovflowd !
